### ISSUE TITLE
startDate column has unique index, but uniqueness is not enforced

### ISSUE THREAD

**Issue by markstos** [mattpker/node-is-master#4]
There's a unique index on the 'startDate' column, however, nothing enforces the uniqueness. It appears that an expectation that `new Date()` will always produce unique result. In our case, this is certainly not the case. 

Our logs are filling up with about 15 million entries which look like this:

```
{ [MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: foo-production.nodes.$startDate_1 dup key: { : new Date(1438769951417) }]
```

(This is across several clusters in several databases, so the indexes and dates involved vary some). 

I think there may be an infinite loop bug here:

https://github.com/mattpker/node-is-master/blob/master/is-master.js#L97

There is an attempt to detect the duplicate case and try a new startDate, but it appears to me that the lines below should change the `startDate` and updatedDate on `this.worker`, not `this`.    

It appears to be this bug is causing an infinite loop in our system, since the function recurses and tries the same wrong value over and over, logging each time....

I'm looking at a patch in our fork right now.

**Comment by mattpker** [comment]
Thanks, yeah it looks like you are correct, I referenced the wrong `this` so the startDate was not updating on the new insert attempt after a fail. I will get this fixed soon unless you already have a pull request in the works.

**Comment by mattpker** [comment]
Should be fixed, I verified that it works properly by forcing the date to a specific date when I was testing. Let me know if you have any other issues.
