### ISSUE TITLE
recommend renaming default collection from 'nodes' to 'is-master'

### ISSUE THREAD

**Issue by markstos** [mattpker/node-is-master#9]
As a default value, the collection name of 'nodes' may conflict with an existing collection due to generic name. Also, the name "node" immediately evokes `node.js` for a Node developer, which is not related to what the collection contains. 

By passing an additional option to Mongoose, we can avoid having the name converted to 'is-masters':

http://stackoverflow.com/questions/22391706/is-there-a-way-to-prevent-mongodb-adding-plural-form-to-collection-names

**Comment by mattpker** [comment]
I don't know if I fully agree with this, for me the name 'nodes' as a collection refers to my running node processes. I added an option to change the collection name in case someone would have a confliction or would want it named something else. 

In addition, changing the default value could be considered a breaking change... i.e. someone has this running in production, they only update one of their servers at a time, and then there is a chance for two to report back as being master at the same time.

I have some ideas for a v2 that would introduce breaking changes as the api would be different. That would probably be a good time to implement this change if needed.

Thanks for the input!
